### ISSUE TITLE
Create a TSX loader

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/amaro#102]

**Comment by AugustinMauroy** [comment]
We will need to use `.swcrc` or `tsconfig.json`

**Comment by marco-ippolito** [comment]
why? we dont use config so far

**Comment by robpalme** [comment]
I don't understand the scope of this issue.

A TSX loader that strips types and outputs JSX seems fine as a standalone library feature. But it would only be useful in Node as a loader if it were chained so that the output can then goes through a JSX loader to make it executable by Node.

Is that the intended use-case?

**Comment by marco-ippolito** [comment]
I mean its not intended for core usage rather than for amaro as standalone loader

**Comment by AugustinMauroy** [comment]
> why? we dont use config so far, its just a matter of stripping types out of tsx and output a valid jsx

You'll agree with me that if you're importing a TSX component, you need to import something ‘javascript frindly’. So to represent a jsx element the transpiler, whatever it is, must transform this jsx into an object. This is why it needs ‘rules’. These are either put in the `tsconfig.json` or the `.swcrc`. These rules allow the transpiler to know that a given jsx element is worth that in a js object. Because JSX is not only used by React. 

So the loader must know how to transpile the TSX/JSX

@JakobJingleheimer Can you confirm? _It was you who originally created the tsx loader_
**REF: ** https://github.com/JakobJingleheimer/nodejs-loaders/blob/main/tsx.mjs

**Comment by marco-ippolito** [comment]
Support for config file goes against the spirit of the typescript support in Node. The tsx loader should output jsx that another loader will consume

**Comment by AugustinMauroy** [comment]
I understand. So can amaro offer two loaders TSX2JSX and JSX2JS? And JSX2JS would not necessarily be used in node core but that users can use themselves.

**Comment by marco-ippolito** [comment]
This would not be used in node core.
The utility I was thinking would be to be able to run next.js in dev mode

**Comment by AugustinMauroy** [comment]
I use Jackob's for unit testing react components. It's the only use I've found at the moment. Because doing SSR with node and a loader would be horrible from a performance point of view.

**Comment by AugustinMauroy** [comment]
And if people want to have a tsx loader based on SWC there is https://github.com/swc-project/swc-node/tree/master/packages/register#readme . So if node core doesn't intend to support `tsx` I think we can close this issue as not planned.

**Comment by JakobJingleheimer** [comment]
> @JakobJingleheimer Can you confirm?

Is the question about whether a config file is required? That depends on the transpiler. For example, `esbuild` configuration is required in order to enable j|tsx handling; BUT we could pass those here (ex if file extension is `.jsx` or `.tsx`) because _which_ (for `esbuild`) is used doesn't matter for the purposes of just getting it to run (ex for component tests).

We'll be publishing the above cited loader probably later this week.
